// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU6OrZdD-Sf9koxJxWT8KUzZl2FTljEcg',
    appId: '1:729850836241:web:a5095f7a0599eccf1c48b0',
    messagingSenderId: '729850836241',
    projectId: 'apniseva-4ddf5',
    authDomain: 'apniseva-4ddf5.firebaseapp.com',
    storageBucket: 'apniseva-4ddf5.appspot.com',
    measurementId: 'G-3EVWJPEY49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8fcXwfivl_MXlGvvH3M0VIicIz7gJvQ',
    appId: '1:729850836241:android:011de6d929b4b8e51c48b0',
    messagingSenderId: '729850836241',
    projectId: 'apniseva-4ddf5',
    storageBucket: 'apniseva-4ddf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqo9F-qheuHvD6tcFWwOqYqO_pVkHH6U',
    appId: '1:729850836241:ios:f187cc663da8bb721c48b0',
    messagingSenderId: '729850836241',
    projectId: 'apniseva-4ddf5',
    storageBucket: 'apniseva-4ddf5.appspot.com',
    iosBundleId: 'com.example.apniseva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUqo9F-qheuHvD6tcFWwOqYqO_pVkHH6U',
    appId: '1:729850836241:ios:f187cc663da8bb721c48b0',
    messagingSenderId: '729850836241',
    projectId: 'apniseva-4ddf5',
    storageBucket: 'apniseva-4ddf5.appspot.com',
    iosBundleId: 'com.example.apniseva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU6OrZdD-Sf9koxJxWT8KUzZl2FTljEcg',
    appId: '1:729850836241:web:af8de18e87509e511c48b0',
    messagingSenderId: '729850836241',
    projectId: 'apniseva-4ddf5',
    authDomain: 'apniseva-4ddf5.firebaseapp.com',
    storageBucket: 'apniseva-4ddf5.appspot.com',
    measurementId: 'G-QTH8E9E79T',
  );
}
